### ISSUE TITLE
An assembly specified in the application dependencies manifest (pokecordcatcher.deps.json) was not found:

### ISSUE THREAD

**Issue by SyncXII** [ExtraConcentratedJuice/pokecord-catcher#10]
So I downloaded the catcher from master-releases since I can't seem to remove the le pokemans catch response on the releases tab even though I used the config from the master-release and disabled catch response.

Now using the version in master-release gives me this error when I run the dotnet. I already installed the dotnet sdk and dotnet from read me.
``Error:
  An assembly specified in the application dependencies manifest (pokecordcatcher.deps.json) was not found:
    package: 'CoreCompat.System.Drawing.v2', version: '5.2.0-preview1-r131'
    path: 'lib/netstandard2.0/CoreCompat.System.Drawing.dll'
``
Thank you!

**Comment by rachelew10** [comment]
Use this [release](https://github.com/ExtraConcentratedJuice/pokecord-catcher/releases)
