### ISSUE TITLE
Meltan and Melmetal

### ISSUE THREAD

**Issue by terlalu123** [ExtraConcentratedJuice/pokecord-catcher#101]
the following pokemon are added in pokecord bot, maybe we can have update poke list?
https://bulbapedia.bulbagarden.net/wiki/Meltan_(Pokémon)
https://bulbapedia.bulbagarden.net/wiki/Melmetal_(Pokémon)

**Comment by Decadescence** [comment]
Save the dev repeating himself, 

You can do it yourself pretty easily, do <pokecord prefix>info meltan/melmetal, open the photos save them and use the hashtool to update your poke.json file.

"meltan":["0x73FF0028A46C7A6B485A634E727C7978807568797B6E80756C756E6E777275747073716E74717074"]

"Melmetal":["0xC0DE00BFD178FFC9EECED9DECBCABDCABABAB4CFCAAED6C4CCB5D0C8BEC5B6C4BBC8C4BEC7B8CFBD"]

save you half the work heres these to your poke.json

**Comment by terlalu123** [comment]
okay thank you very much for your information and help @Decadescence
