### ISSUE TITLE
WhitelistedGuilds not working properly + can I ask for a new feature, like to delay catching so it looks human like?

### ISSUE THREAD

**Issue by SyncXII** [ExtraConcentratedJuice/pokecord-catcher#11]
So I have total of 3 guilds whitelisted that I don't want to catch pokemon from, because I don't want to get banned in it since they spawn on all text-channels which is too risky.

But sadly even though its whitelisted, its still catching on those whitelisted servers? I also tried the other way around, like putting servers i only want to catch pokemons from and still the same.

I'm using Release 4 of the bot.

Also could I ask a feature request? Like delaying a catch so it would look human like.

Thank you!

**Comment by SyncXII** [comment]
I see so that's what i'm missing thanks. I'll try again. But however I wonder why I cannot use the bot command. I dont get any reply when I type &status on discord. I tried typing on the command prompt but you can't. Sorry if i'm newbie in this. Thank you! Good work btw.

**Comment by rachelew10** [comment]
I am not the creator of the bot so all credit goes to ExtraConcentratedJuice; however I too had these problems & just doing my bit for the community.

Do you have your discord ID in the "OwnerID" variable of the config file? You can find your ID by going to the developer mode in discord & right clicking your user in any server then "copy ID".

**Comment by SyncXII** [comment]
Oh I see goddamn lol. Looks like i'm doing it all wrong. I'm trying to get the id from user#1234 lol. Thanks mate. Now all my problems are fixed. xD
