### ISSUE TITLE
Sometimes bot is connected, running and ready, but not catching anything. Also the userbot command status not showing anything.

### ISSUE THREAD

**Issue by SyncXII** [ExtraConcentratedJuice/pokecord-catcher#12]
I encountered this a lot of times. Like today I was catching some pokemons on my own server and suddenly it stopped. So logged out my account and relogin to get a new token, and updated it with the new token but it still says Ready but not doing anything and cant check the status of the bot itself.

Also is there an issue if I use a token with 2FA enabled?

Also would it be possible to add WhitelistGuildChannel so I can only set and catch on whitelisted channel in said Guild.

Also sometimes i'm getting this error;
``[Warning] Unknown Dispatch (SESSIONS_REPLACE)``

Thanks!

**Comment by ExtraConcentratedJuice** [comment]
you'll probably get some issues with 2fa, never tested it so idk

I've also run into the bot not responding to shit issue, seems to happen sporadically. I'll look into it later i guess. I can also take a look at adding channel whitelists, yeah

no idea what SESSIONS_REPLACE is, it's probably something relating to user accounts.

**Comment by SyncXII** [comment]
Alright thanks. Looking forward for next update!

**Comment by Man-not** [comment]
I had that too, but the problem was just that I hadn't set the pokecord prefix to "p!" in the config file. Hopefully that helps
