### ISSUE TITLE
Suggestion: Spammer

### ISSUE THREAD

**Issue by eco999** [ExtraConcentratedJuice/pokecord-catcher#13]
Spams a chosen channel in order to spawn pokemon.

**Comment by SyncXII** [comment]
You can use this alternatively;
https://github.com/davyvong/pokebot

**Comment by ExtraConcentratedJuice** [comment]
I'll add a spammer module or something when I fix the shitcode i guess

**Comment by eco999** [comment]
Thanks for the consideration of adding a spammer module.
Thanks SyncXII for this. This is much better than my Discord in a VM + AutoHotKey spam script combo.

**Comment by ExtraConcentratedJuice** [comment]
added a spammer on the latest release
