### ISSUE TITLE
unhandled exception error

### ISSUE THREAD

**Issue by Twill1016** [ExtraConcentratedJuice/pokecord-catcher#134]
Unhandled Exception: Newtonsoft.Json.JsonReaderException: Unexpected character encountered while parsing value: M. Path 'Token', line 2, position 11.

idk what it means

**Comment by Nayshjin** [comment]
You have a problem with your token ID ..I am guessing you entered it with the # hastag ..remove the hashtag and it should be fine

**Comment by Twill1016** [comment]
> You have a problem with your token ID ..I am guessing you entered it with the # hastag ..remove the hashtag and it should be fine

i never did have a hastag. i got the token again, just in case, but to no avail. when i did try running it again, it said the issue was at position 10 rather than 11 which i thought was curious.

**Comment by Twill1016** [comment]
> > You have a problem with your token ID ..I am guessing you entered it with the # hastag ..remove the hashtag and it should be fine
> 
> i never did have a hastag. i got the token again, just in case, but to no avail. when i did try running it again, it said the issue was at position 10 rather than 11 which i thought was curious.

says something wrong "Token": Mj
                                                 ^here
