### ISSUE TITLE
Whitelist On Channels/Servers

### ISSUE THREAD

**Issue by Dreyannz** [ExtraConcentratedJuice/pokecord-catcher#14]
The Bot Works Perfectly than what Ive Expected.

can you add a feature that would only catch on a certain channel/server?

**Comment by rachelew10** [comment]
Use guild whitest for server whitelist

On 15 Jul 2018, at 14:20, Adrian Jann Octat <notifications@github.com<mailto:notifications@github.com>> wrote:


The Bot Works Perfectly than what Ive Expected.

can you add a feature that would only catch on a certain channel/server?

**Comment by Dreyannz** [comment]
Already Place the ID of the Server/Channel to the whitelist and typed &reload on discord. still says WhitelistGuilds: False

**Comment by rachelew10** [comment]
You need to toggle it to true either in the config or send the command to the bot

**Comment by ExtraConcentratedJuice** [comment]
run &toggleguilds

**Comment by Dreyannz** [comment]
thanks for your time. really appreciate it
