### ISSUE TITLE
Poke.json missing or has some mistakes

### ISSUE THREAD

**Issue by hyquoccuong** [ExtraConcentratedJuice/pokecord-catcher#142]
Pokemon names:
Frillish
Jellicent
Shellos
Gastrodon
Pyroar
Basculin
Feebas(?)
They use male and female pokemon images. Examples:
[Frillish](https://media.discordapp.net/attachments/555246088194621440/555777070819442698/PokecordSpawn.jpg)
[Jellicent](https://cdn.discordapp.com/attachments/555246088194621440/555580297366732800/PokecordSpawn.jpg)

And almost Alolan Pokemons, I think because the images use for hashtool is not correct

**Comment by sheppoo** [comment]
there's an updated pokemon file

**Comment by hyquoccuong** [comment]
> there's an updated pokemon file

@sheppoo yes I got it
