### ISSUE TITLE
HRESULT: 0x80070057

### ISSUE THREAD

**Issue by infernooo** [ExtraConcentratedJuice/pokecord-catcher#145]
![Screenshot - 3_19_2019 , 1_26_30 AM](https://user-images.githubusercontent.com/40263169/54559478-2bf08700-49e6-11e9-852a-7cc0b4f7ac73.png)

I am getting this error!

**Comment by Twill1016** [comment]
is your directory right?

**Comment by infernooo** [comment]
Yah it was. i googled the error got the fix!
