### ISSUE TITLE
I don't know how to run this 

### ISSUE THREAD

**Issue by th3l3x** [ExtraConcentratedJuice/pokecord-catcher#152]
When I try to run it, this happens.
[![Screenshot from Gyazo](https://gyazo.com/81113fbb9f39c441f9156b6ece485df0/raw)](https://gyazo.com/81113fbb9f39c441f9156b6ece485df0)

**Comment by th3l3x** [comment]
ok so ive gotten to this point what do I do now
[![Screenshot from Gyazo](https://gyazo.com/4b4d5d81cdb2c189782b2a51e8a9bee4/raw)](https://gyazo.com/4b4d5d81cdb2c189782b2a51e8a9bee4)

**Comment by Twill1016** [comment]
your bot should be working fine. if not, have you configured config.json?

**Comment by th3l3x** [comment]
when i run it, it doesnt catch anything and keeps displaying unknown

**Comment by Twill1016** [comment]
> when i run it, it doesnt catch anything and keeps displaying unknown

could i get a screen shot?

**Comment by th3l3x** [comment]
Can you step by step tell me what to do
Does this make a bot in your discord or like what does it do

**Comment by th3l3x** [comment]
ok now ive gotten it to work and but it doesnt catch anything

**Comment by th3l3x** [comment]
i figured it out thanks for all the help though!

**Comment by jamboelite93** [comment]
How did you figure it out because mines still does not work :(

**Comment by jamboelite93** [comment]
> How did you figure it out because mines still does not work :(



> i figured it out thanks for all the help though!
