### ISSUE TITLE
[Warning] Serializer Error

### ISSUE THREAD

**Issue by SyncXII** [ExtraConcentratedJuice/pokecord-catcher#17]
I keep on getting this error for some time now, the bot still works but sometimes when I get this error, the bot stops working. Which caused me to miss 2 legendary spawns on my server. What could this mean? I'm already using the Release 7. Only had Whitelist Guilds and Spammer On.

`[Warning] Serializer Error
[Warning] Serializer Error
[Warning] Serializer Error
[Warning] Serializer Error`

**Comment by ExtraConcentratedJuice** [comment]
I've never gotten that error before, did you change anything else at all?

**Comment by SyncXII** [comment]
Nothing. Just those that I mentioned. The rest are default values from
config like catch delay and spammer delay.

**Comment by ExtraConcentratedJuice** [comment]
Can you try to compile a debug build of the source and run with that for a while? It might log some more detailed information.
