### ISSUE TITLE
SpammerBot creates Unhandled Exception

### ISSUE THREAD

**Issue by Idklife** [ExtraConcentratedJuice/pokecord-catcher#20]
Unhandled Exception: System.NullReferenceException: Object reference not set to an instance of an object.
   at PokecordCatcherBot.Modules.SpammerService.DoSpam() in E:\stuff\PokecordCatcher\PokecordCatcher\PokecordCatcher\Modules\SpammerService.cs:line 30
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location where exception was thrown ---
   at System.Threading.ThreadPoolWorkQueue.Dispatch()

This issue only occurs when I turn on spammer through bot commands, the bot won't work after a restart and I have to download a new release.

**Comment by ExtraConcentratedJuice** [comment]
You can delete state.data to manually turn the spammer off. I'm guessing that you supplied an invalid channel ID to the SpamChannelID in the configuration.

**Comment by Idklife** [comment]
Thanks for the reply, I was a bit sleepy last night and it turns out I put my serverID down instead of my channelID in the config.
Sorry, another question;
How do I use the [prefix]trade [pokemon] bot command?
When I type the command down, the bot searches for all pokemon by its name and then attempts to start a trade offer to myself.
Thanks for your help ^^

**Comment by ExtraConcentratedJuice** [comment]
That's how it's supposed to work, I guess I'll add a pokemon ID parameter or something later
