### ISSUE TITLE
Error when running 'dotnet PokecordCatcher.dll' in cmd.exe

### ISSUE THREAD

**Issue by InstallInstances** [ExtraConcentratedJuice/pokecord-catcher#21]
The following response is sent back
![83dc17a4385f6d47283d985c4fc08e57](https://user-images.githubusercontent.com/41493325/43028647-0724e3a8-8c4f-11e8-98bb-080740d06687.png)

**Comment by tylerebowers** [comment]
me too
![capture](https://user-images.githubusercontent.com/29521795/43036822-975657dc-8cd5-11e8-845e-c39184b148cb.JPG)

**Comment by ExtraConcentratedJuice** [comment]
Did you guys somehow download the source code instead of the [Release](https://github.com/ExtraConcentratedJuice/pokecord-catcher/releases/download/1.6.0/Release.zip)?

**Comment by tylerebowers** [comment]
yep

**Comment by SuperBossDude** [comment]
I'm getting the same error and I have no idea why, i downloaded the release, configured the important stuff, and I have an "application extension" type file named PokecordCatcher.dll . Also I'm very new to this kind of thing so go easy if it's painfully obvious what I'm doing wrong
![pokecord catcher](https://user-images.githubusercontent.com/41771157/43302486-c5d5be2e-9138-11e8-9b9f-4bd368bedcab.PNG)

**Comment by ExtraConcentratedJuice** [comment]
you're not operating in the correct directory.
run `cd C:/My/Directory/Here` before running dotnet PokecordCatcher.dll

**Comment by Arnish** [comment]
hold shift then right click the entire folder, wherever it is that you extracted it. then click "open command window here." Also make sure you get the capital-lowercase right. It should be **dotnet PokecordCatcher** not **PokeCordCatcher**

**Comment by SuperBossDude** [comment]
Alright figured it out, thanks guys
