### ISSUE TITLE
Thanks ExtraConcentratedJuice

### ISSUE THREAD

**Issue by kyuichi007** [ExtraConcentratedJuice/pokecord-catcher#22]
Thanks for making this awesome tool (y).
But i want asking something. How to add pokemon name and chace, like i want to add tapu koko, tapu fini, etc to to poke.json, how to find the code to that pokemon?
Thanks before Master.

**Comment by ExtraConcentratedJuice** [comment]
You'd have to use [HashTool](https://github.com/ExtraConcentratedJuice/pokecord-catcher/tree/master/HashComputer), I haven't released a compiled version yet though. I'll do it later.
