### ISSUE TITLE
Shiny Pokemon

### ISSUE THREAD

**Issue by Rayden1124** [ExtraConcentratedJuice/pokecord-catcher#27]
So they've added shiny pokemon to the bot now. Will the bot catch them or do you have to update it to the poke.json

**Comment by IimeIine** [comment]
They said the images still look the same and you'll only know if it's a shiny once you caught it, so maybe no need for an update?

**Comment by Arnish** [comment]
don't think there's any need for an update

**Comment by ExtraConcentratedJuice** [comment]
yeah if it changes then somebody can reopen this issue idk
