### ISSUE TITLE
Hash Tool help

### ISSUE THREAD

**Issue by Arnish** [ExtraConcentratedJuice/pokecord-catcher#28]
Hey I have a few questions for when hashing pokemon after running the DLL file via terminal:
1. Which file from bulbapedia or wherever do we download for the hash
2. I downloaded the image and the link on the pokemon number from bulbapedia and linked the path when prompted but it gave an error and closed.

Any help is appreciated, once again thanks to ECJ for this amazing bot that he actually updates often <3

**Comment by NoFiixx** [comment]
Just came to do the same post that you... lets hope the creator see's this and explain how to....

Some hash's pokemon that there wrong: 

Terrakion
Cresselia
Moltres

:·)

**Comment by Arnish** [comment]
There's a bit more than that haha, I haven't been writing them down though because I didn't think it was that important. But it caught my attention and I wanna learn how to do this :, )

**Comment by NoFiixx** [comment]
Yep just see a few more ones, Popplio with the hash of Chespin... xD

**Comment by ExtraConcentratedJuice** [comment]
Usually the 600x600 images work best. These images:

https://bulbapedia.bulbagarden.net/wiki/File:003Venusaur.png

HashTool you just place the image in the same directory as HashGenerator.dll and run

`dotnet HashGenerator.dll yourfilename.png`

**Comment by NoFiixx** [comment]
i will give it a try, Thanks @ExtraConcentratedJuice :·)

**Comment by ExtraConcentratedJuice** [comment]
ill take a look at them later i guess

**Comment by bananas869** [comment]
Sorry to revive but.

Whenever I try to add pokemon, I get this error to the pokemon that his just before the new ones I added. What am I doing wrong?


C:\Users\User\Desktop\publish>dotnet PokecordCatcher.dll

Unhandled Exception: Newtonsoft.Json.JsonReaderException: Invalid character afte
r parsing property name. Expected ':' but got: 0. Path 'Toxicroak', line 1, posi
tion 78469.
   at Newtonsoft.Json.JsonTextReader.ParseProperty()
   at Newtonsoft.Json.Linq.JContainer.ReadContentFrom(JsonReader r, JsonLoadSett
ings settings)
   at Newtonsoft.Json.Linq.JContainer.ReadTokenFrom(JsonReader reader, JsonLoadS
ettings options)
   at Newtonsoft.Json.Linq.JObject.Load(JsonReader reader, JsonLoadSettings sett
ings)
   at Newtonsoft.Json.Linq.JObject.Parse(String json, JsonLoadSettings settings)

   at PokecordCatcherBot.Services.CatcherService.LoadPokemon(String hashPath) in
 E:\stuff\PokecordCatcher\PokecordCatcher\PokecordCatcher\Services\CatcherServic
e.cs:line 96
   at PokecordCatcherBot.Services.CatcherService..ctor(PokecordCatcher bot, Stri
ng hashPath) in E:\stuff\PokecordCatcher\PokecordCatcher\PokecordCatcher\Service
s\CatcherService.cs:line 22
   at PokecordCatcherBot.PokecordCatcher..ctor() in E:\stuff\PokecordCatcher\Pok
ecordCatcher\PokecordCatcher\PokecordCatcher.cs:line 46
   at PokecordCatcherBot.Program.Main() in E:\stuff\PokecordCatcher\PokecordCatc
her\PokecordCatcher\Program.cs:line 11

C:\Users\User\Desktop\publish>

(cmd crashes)

![image](https://user-images.githubusercontent.com/42307966/44184908-94564d80-a111-11e8-8a56-6c4d5cf33f5a.png)
