### ISSUE TITLE
Problem with Command Prompt part?

### ISSUE THREAD

**Issue by IlikeDespacito2** [ExtraConcentratedJuice/pokecord-catcher#30]
everytime I type in (or copy and paste) PokecordCatcher.dll in cmd prompt it says "No executable found matching command "dotnet-PokecordCatcher.dll" can you help me?

**Comment by ExtraConcentratedJuice** [comment]
https://github.com/ExtraConcentratedJuice/pokecord-catcher/issues/21

**Comment by IlikeDespacito2** [comment]
um sorry im just a stupid kid so i dont understand the "cd C:/My/Directory/Here" thing. can you help me?
sorry for wasting your time
