### ISSUE TITLE
teech me

### ISSUE THREAD

**Issue by IlikeDespacito2** [ExtraConcentratedJuice/pokecord-catcher#31]
sorry im just a stupid little kid so i dont understand the "cd C:/My/Directory/Here" thing
sorry for wasting your time

**Comment by IlikeDespacito2** [comment]
i just need help on the bot directory thing ;-; im dum

**Comment by ExtraConcentratedJuice** [comment]
https://helpdeskgeek.com/how-to/open-command-prompt-folder-windows-explorer/
