### ISSUE TITLE
more broken pokemon

### ISSUE THREAD

**Issue by Rayden1124** [ExtraConcentratedJuice/pokecord-catcher#32]
So i just posted about Pyukumuku.
And apparently Aegislash is messed up now too.
https://gyazo.com/2cab7b9577f6e519ef0e4213d1670cb3
Screen shot^
Aegislash used to work idk what happened.

**Comment by GoldenBlaster** [comment]
same issue with me
![screenshot_3](https://user-images.githubusercontent.com/39948121/43352587-6a2d34f6-9243-11e8-87f9-de09a36bd63f.png)
![screenshot_4](https://user-images.githubusercontent.com/39948121/43352590-6d774ea8-9243-11e8-8458-4a32488e9fef.png)

**Comment by ExtraConcentratedJuice** [comment]
yeah aegislash used to be a 2 in one image, i'll fix it later i guess.

as for nidoran that'll be fixed when i fix up the pokemon lookup system
