### ISSUE TITLE
Several more broken pokemon

### ISSUE THREAD

**Issue by Rayden1124** [ExtraConcentratedJuice/pokecord-catcher#34]
I've made a couple issues for a couple broken pokemon but i've just woke up kinda scrolling through seeing what i got over night and i'm seeing several broken pokemon. I'm not trying to bug you with constant issues i'm just trying to let your know. There's like a lot of them broken now that used to work.

Examples: 
Aegislash, Nidoran♂, Nidoran♀, Pyukumuku, Morelull, Spoink, Oricorio, Torkoal, Dhelmise, Gulpin, Aipom, Clauncher, Walrein, Sandygast, Bruxish, Wishiwashi, Araquanid, Cutiefly, Mudsdale, Fomantis, Zigzagoon, Charjabug, Jumpluff, Swablu, Mareanie, Cubchoo, Barboach, Steenee, Lurantis, Wimpod, Rowlet, Oranguru, Komala, Pumpkaboo, Wailord, Bounsweet, Stufful.

These are the ones i seen overnight, i'm sure there are more broken ones.

**Comment by ExtraConcentratedJuice** [comment]
I've done something with this release that will probably fix the bot failing to detect the names properly. Come back and close this issue if it works.

https://github.com/ExtraConcentratedJuice/pokecord-catcher/releases/tag/1.6.2

**Comment by Rayden1124** [comment]
Ok i will try it when i wake up

**Comment by ExtraConcentratedJuice** [comment]
I've been running the bot for a while now and have seen it working fine since the latest release, closing this issue
