### ISSUE TITLE
Detection

### ISSUE THREAD

**Issue by Grock123** [ExtraConcentratedJuice/pokecord-catcher#37]
I seen people's pokemon get wiped and their balance due to self-bots by pokecord, any idea how it detects it and how we can avoid that happening?

Thanks!

**Comment by IdontKnowMuchAtAll** [comment]
I think detection happens when using the keywords for example togglepokemon/toggleguilds, so maybe we can have the option in config to change our commands (I am not sure, it just seems like the easiest way to check for selfcatchers)

**Comment by ExtraConcentratedJuice** [comment]
Gonna add some alias shit to commands and some random delays to stay under the radar I guess

**Comment by Grock123** [comment]
If that's how the detection is happening we would greatly appreciate it. 

thanks for response.
