### ISSUE TITLE
whitelist guild not working

### ISSUE THREAD

**Issue by GreenXpqser** [ExtraConcentratedJuice/pokecord-catcher#4]
or is it the server not channel

 if channel please add channel whitelisting

**Comment by GreenXpqser** [comment]
also gourgeist is identified as jolteon

**Comment by GreenXpqser** [comment]
Tapu Koko as manectric

**Comment by ExtraConcentratedJuice** [comment]
yeah there are some issues with the pokemon that i scraped, didn't catch all of them

if you want you can hash them yourself using the hashing tool and paste them into poke.json then submit a pull request
