### ISSUE TITLE
help me

### ISSUE THREAD

**Issue by moocow1995** [ExtraConcentratedJuice/pokecord-catcher#41]
having trouble, i am doing all the things the guide said to do
first i downloaded the release zip
i extracted it to my desktop
i configed the confige.json
then i instead .netcore
then i opened cmd and typed in "dotnet PokecordCatcher.dll"
then i get No "executable found matching command "dotnet-PokecordCatcher.dll" "

**Comment by Grock123** [comment]
you need to run that command in the bot directory, open up command and type cd [Paste bot directory] aka location of the bot stored on your computer, then run the command ''dotnet PokecordCatcher.dll'' no **-**.

**Comment by moocow1995** [comment]
ahh
thanks dwag
