### ISSUE TITLE
Not sure whats happening but error in CMD

### ISSUE THREAD

**Issue by ZorgStar** [ExtraConcentratedJuice/pokecord-catcher#45]
![image](https://user-images.githubusercontent.com/42191747/43808963-718fccc4-9aa7-11e8-880f-36edd3c73fb8.png)

**Comment by ZorgStar** [comment]
Ends Run for bot

**Comment by ExtraConcentratedJuice** [comment]
make sure the spammer channel in your config is set to a valid channel
