### ISSUE TITLE
I have no idea what's wrong

### ISSUE THREAD

**Issue by idontknow134** [ExtraConcentratedJuice/pokecord-catcher#48]
![image](https://user-images.githubusercontent.com/42282112/43979610-385ce93a-9ce3-11e8-9387-5e157555a4fb.png)
I'm sort of okay w/ cmd,, but I don't understand what's gone wrong

**Comment by ExtraConcentratedJuice** [comment]
Make sure the spammer channel in your config is set to a valid channel

**Comment by idontknow134** [comment]
Thank you, I missed that! Now, there seems to be no issues!

**Comment by idontknow134** [comment]
![2018-08-11_11-49-47](https://user-images.githubusercontent.com/42282112/43991068-d11c4156-9d5c-11e8-897a-42de7e010c12.png)
It seems this is misnamed?

**Comment by ExtraConcentratedJuice** [comment]
yeah, the bot is still using the old aegislash picture. gotta fix that i guess
