### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by bananas869** [ExtraConcentratedJuice/pokecord-catcher#50]
Is there a way to disable catching? want to setup a spam only account..

**Comment by Grock123** [comment]
togglepokemon - toggles pokemon whitelisting maybe if you set it to a pokemon that doesn't exist, not sure if there is a way.

**Comment by tokenluck** [comment]
^Using a macro is a pretty simple way to do spam only.

**Comment by bananas869** [comment]
yea whitelist worked, thank you ♥
