### ISSUE TITLE
Missing/Wrong Pokemon

### ISSUE THREAD

**Issue by bananas869** [ExtraConcentratedJuice/pokecord-catcher#53]
FAQ
Q: yo why is the bot recognizing some pokemon as other pokemon

A: I scraped the shit out of bulbapedia for the pokemon list so it isn't perfect, just use the hashing tool to hash and add pokemon to poke.json

Could you explain a little more how to do this? I could fix the pokemon list for you and upload it.

**Comment by Arnish** [comment]
https://github.com/ExtraConcentratedJuice/pokecord-catcher/issues/28#issuecomment-408297465

Explained here

**Comment by bananas869** [comment]
thank you ♥ @Arnish
