### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by Visilex** [ExtraConcentratedJuice/pokecord-catcher#59]
Welcome to .NET Core!
---------------------
Learn more about .NET Core @ https://aka.ms/dotnet-docs. Use dotnet --help to see available commands or go to https://aka.ms/dotnet-cli-docs.

Telemetry
--------------
The .NET Core tools collect usage data in order to improve your experience. The data is anonymous and does not include command-line arguments. The data is collected by Microsoft and shared with the community.
You can opt out of telemetry by setting a DOTNET_CLI_TELEMETRY_OPTOUT environment variable to 1 using your favorite shell.
You can read more about .NET Core tools telemetry @ https://aka.ms/dotnet-cli-telemetry.
No executable found matching command "dotnet-PokecordCatcher.dll"

**Comment by ExtraConcentratedJuice** [comment]
Download the release and not the source code. Run the command in the bot's directory
