### ISSUE TITLE
How to start the bot

### ISSUE THREAD

**Issue by boiluis7** [ExtraConcentratedJuice/pokecord-catcher#64]
I can't figure out how to even run the bot or start it up

'navigate to your bot directory, open a command prompt'
How do you do that?

**Comment by Grock123** [comment]
Open command prompt > type cd > paste the path where the mod is located > run dotnet PokecordCatcher.dll..

**Comment by boiluis7** [comment]
Ahhhh okay thanks! But one more thing I got it the auto catcher to run, how do I get it to spam messages by itself?

**Comment by Grock123** [comment]
whatever prefix you have ''!''togglespam
