### ISSUE TITLE
Autocatcher mistakens Aegislash for Suicune.

### ISSUE THREAD

**Issue by shakgithub** [ExtraConcentratedJuice/pokecord-catcher#65]
A few minutes ago from the time I'm making this post, a aegislash spawned on my pokecord channel and the bot that's configured with this program tried to catch it like it was a suicune. which explains why a suicune spawned a few days ago and it didn't catch it. can you update the program with a fix to this?

**Comment by Grock123** [comment]
Download the recent release, pretty sure it's fixed because it caught a suicune for me.

**Comment by shakgithub** [comment]
Thank you. I'm going to download the latest version right now.
