### ISSUE TITLE
I have a problem.

### ISSUE THREAD

**Issue by realtirey** [ExtraConcentratedJuice/pokecord-catcher#72]
C:\WINDOWS\system32>dotnet PokecordCatcher.dll
No executable found matching command "dotnet-PokecordCatcher.dll"

This is when I run "dotnet PokecordCatcher.dll" in CMD.

**Comment by dasokudesu** [comment]
Go into your CMD, I guess, and then do cd Desktop, and then cd publish, and then do the command, hopefully that should work.

**Comment by realtirey** [comment]
```
C:\Users\User>cd Desktop

C:\Users\User\Desktop>cd publish
The system cannot find the path specified.

C:\Users\User\Desktop>dotnet PokecordCatcher.dll
No executable found matching command "dotnet-PokecordCatcher.dll"

C:\Users\User\Desktop>
```
Note that I changed my name to "User" in the code im posting here.

**Comment by ExtraConcentratedJuice** [comment]
Navigate to the directory that you extracted the bot to. It should be clear that you cannot run something that isn't even in the folder that you are in.

**Comment by realtirey** [comment]
I don't understand what you mean.

**Comment by realtirey** [comment]
can you elaborate?
