### ISSUE TITLE
Issues...

### ISSUE THREAD

**Issue by dasokudesu** [ExtraConcentratedJuice/pokecord-catcher#74]
In the CMD, I see, "Unknown User (PRESENCE_UPDATE User = [random string of numbers]"
Or also, how the heck do I even type to the bot in the first place, I'm pretty sure I'm stupid, but help is appreciated.

**Comment by ExtraConcentratedJuice** [comment]
Nothing to worry about. Type commands on Discord.

**Comment by dasokudesu** [comment]
Like, just in discord, in general. Even if so, I don't think that works?
