### ISSUE TITLE
halp

### ISSUE THREAD

**Issue by actualtotalnoob** [ExtraConcentratedJuice/pokecord-catcher#75]
I spent 3h trying to figure out how to configure and what to download, shit told me to turn on iis, i did, shit told me to get admin status, i did, and now...
![image](https://user-images.githubusercontent.com/43576304/46017105-43bb1280-c109-11e8-8cf7-776d8fabe5b3.png)

**Comment by dasokudesu** [comment]
Go into CMD, type cd desktop, and then cd publish, and then type dotnet PokecordCatcher.dll and it should work.

**Comment by ExtraConcentratedJuice** [comment]
You have to navigate to the directory that you extracted the release archive to
