### ISSUE TITLE
what am i doing wrong?

### ISSUE THREAD

**Issue by thatonecookie** [ExtraConcentratedJuice/pokecord-catcher#76]
bot isnt working
i did the steps and downloaded release
Download, install the .NET Core runtime from HERE

Navigate to your bot directory and open a command prompt, then run this command:

dotnet PokecordCatcher.dll
i did this and its not working
this is the error i get
![image](https://user-images.githubusercontent.com/43299487/46045890-a51cba80-c0e4-11e8-881f-5c846d285717.png)

**Comment by dasokudesu** [comment]
Okay, so, go into CMD, type cd Desktop, then cd publish, and then type dotnet PokecordCatcher.dll, and it should do the thing.

**Comment by thatonecookie** [comment]
got it to work
