### ISSUE TITLE
how do commands work

### ISSUE THREAD

**Issue by thatonecookie** [ExtraConcentratedJuice/pokecord-catcher#78]
i tried typing them in and it didnt put anything in so how do they work

**Comment by dasokudesu** [comment]
Okay, so you need to go to the bot, and since your prefix for the bot is probably automatically -, you'd go to the pokecord bot, and dm it -togglepokemon, and it should work.

**Comment by thatonecookie** [comment]
its not working i pmed the pokecord bot my prefix is ! btw 
![image](https://user-images.githubusercontent.com/43299487/46113489-3a3ab480-c1b4-11e8-8b2a-8cbb0954c330.png)

**Comment by dasokudesu** [comment]
Make your prefix p!, try that, if it doesn't work let me know.

**Comment by thatonecookie** [comment]
Nope same error 
![image](https://user-images.githubusercontent.com/43299487/46191808-765a3c00-c2be-11e8-9fce-b9311bd92f67.png)

**Comment by jagrag** [comment]
I'm getting the same error

**Comment by jagrag** [comment]
I was getting the same problem. My mistake was simple. I had put the prefix I wanted to use under the "pokecord prefix" instead of the "userbot" prefix

**Comment by ExtraConcentratedJuice** [comment]
resolved in the latest release

**Comment by thatonecookie** [comment]
> resolved in the latest release

will the bot give a respond if the a command worked because im trying the commands and i cant tell if they are working or not
