### ISSUE TITLE
Helping Hand for Everyone

### ISSUE THREAD

**Issue by dasokudesu** [ExtraConcentratedJuice/pokecord-catcher#80]
Hi, so, as you all probably don't know, some of you are having trouble with the bot, so I made it simpler, instead of having to do Windows + R combination, or typing in CMD in the search bar, I made it all one batch file that says, hey, go to desktop, then the file, and run the dll, easy as that. Here it is!
[PokecordBatch.zip](https://github.com/ExtraConcentratedJuice/pokecord-catcher/files/2421801/PokecordBatch.zip)
It's completely safe, you can literally check out the Batch file yourself by right clicking on it, and pressing edit with notepad, or edit with Notepad++, enjoy just to reduce time.

**Comment by ExtraConcentratedJuice** [comment]
will not work if you do not have the release extracted to your desktop

i might have to include something like this in a later release since everybody seems clueless on how to navigate to the correct directory
