### ISSUE TITLE
Error 401: Unauthorized

### ISSUE THREAD

**Issue by iamwumpus** [ExtraConcentratedJuice/pokecord-catcher#90]
Unhandled Exception: Discord.Net.HttpException: The server responded with error 401: 401: Unauthorized

on a MacBook Pro, 64bit ._.

**Comment by OnlyRedx** [comment]
You have the wrong token ID in your config.

**Comment by tparadise33** [comment]
OnlyRedx, if you know how to find your discord token ID, I would appreciate it if you would tell me because I cannot find it with the new update that they did.

**Comment by OnlyRedx** [comment]
https://discordhelp.net/discord-token

**Comment by OnlyRedx** [comment]
https://discordhelp.net/discord-token
