### ISSUE TITLE
Problem With Running

### ISSUE THREAD

**Issue by czaroslav333** [ExtraConcentratedJuice/pokecord-catcher#92]
i were doing it what did u said but some of this isnt simple explained so i didnt understood some of them.
what shloud i do when i configure config.json? and when i put dotnet hosting i installed it and nothing happenend. If someone can record how do i do this stuff i will be very thankfull.
![przechwytywanie](https://user-images.githubusercontent.com/44734780/47957281-0fadf980-dfb3-11e8-8ac7-46664269c142.PNG)

**Comment by czaroslav333** [comment]
Im sorry if u cant understand i am bad at english

**Comment by ExtraConcentratedJuice** [comment]
read the instructions again
