### ISSUE TITLE
discord user token

### ISSUE THREAD

**Issue by tparadise33** [ExtraConcentratedJuice/pokecord-catcher#96]
I have no idea how to find this, does anybody know how?

**Comment by AgricioL** [comment]
https://www.youtube.com/watch?v=drX1M9vW7fE

**Comment by Jorogumo4** [comment]
It's different now. Inside of the discord app follow these steps.

1. Press control shift i --- Go to "Network" at the top.
2. Click in the white open space and press F5
3. In the filter bar at the top type "/api/v6"
4. In the list of names click on "Applications"
5. Ensure you're on the "Headers" tab after selecting "Applications"
6. Scroll down until you see "Authorization"
7. If you do not see this go to the second "Applications" on your list.
8. Copy that "Authorization" ID and paste it in the config.json you opened beside of "Token"
